sayterdarkwynd/FrackinRaces

items/active/shields/shield.lua
Added more verbose debugging. Attempted a fix for the infinitely-increasing damage buff. Be sure to set debug to false before pushing
this live.
=> Shield buff fix, maybe. Also debug

items/active/shields/shield.lua
=> Another attempt at block bonus removal

items/active/shields/shield.lua
update it anyway, that way you'll have my current version of the file
=> Another failed attempt

items/active/shields/shield.lua
This *should* be sufficient. I've tested on collisions but not damage from status effects.
=> Fix perfect block bonus not being cleared on any damage being received.

items/active/weapons/melee/meleecombo.lua
Should zero out properly now after the combo is done
=> One-handed Melee Combo bonuses fix

interface/scripted/mmupgrade/mmupgradegui.lua, interface/scripted/mmupgrade/mmupgradegui.original.config.patch
Stops MM upgrades from being broken, again.
=> Yet Another MM Upgrade Fix

interface/scripted/statWindow/statWindow.config, interface/scripted/statWindow/statWindow.lua
Changes:
- Refresh button removed; window refreshes automatically
- Data moved to a config file
- "validRaces" stuff removed (unnecessary; invalid images in widgets just show up blank)
- Optimizations and code reworking
- Fixed small typo on Gas Immunity causing color to appear as characters
=> StatWindow rewrite

stats/effects/food/robofood.lua
Glitches won't turn into Terminators after taking a bite out of an
automato anymore.
=> Fixed Robofood causing the singularity

interface/scripted/statWindow/statWindow.config, interface/scripted/statWindow/statWindow.lua
Included all custom races in the status window as a temporary solution
pending a more definitive one.
Possible fix for racial effect line being blank for most races.
=> Inclusion of Custom Races for Status Window

scripts/FRHelper.lua, scripts/raceEffects.config, stats/bonuses/aerialEffect.lua, stats/raceability.lua
Added a helper script that makes scripting FR stuff easier.
raceability.lua should no longer spam the log about uninit errors.
Revised raceability.lua and aerialeffect.lua to use the new helper script.
Please ignore anything script or weapon related in the helper script, it's unfinished stuff that doesn't affect anything at the moment.
=> Helper script and script updates

interface/scripted/statWindow/statWindow.config, scripts/raceEffects.config, species/phox.species.patch, stats/effects/deprecated/racephox.statuseffect
First time using Github, let me know if I can do anything to make it easier on you.
Changed files: 
raceEffects.config, (Because it's the core of the mod) 
statWindow.config (Added phox to list of creatures the tricorder works on)
Added files: 
racephox.statuseffect, 
phox.species.patch
Thanks for doing this for me!
=> Phox addition

interface/scripted/mmupgrade/mmupgradegui.config.patch, interface/scripted/mmupgrade/mmupgradegui.lua
=> MM updates

species/neko.species.patch
Just adding a little flavor to the race description. Cat is free to change this as they see fit.
=> Adding Flavor

species/apex.species.patch, species/avali.species.patch, species/avian.species.patch, species/callistan.species.patch, species/felin.species.patch, species/floran.species.patch, species/glitch.species.patch, species/greckan.species.patch, species/lamia.species.patch, species/novakid.species.patch, species/viera.species.patch
Added additional flavor text to various race tooltips.
=> Flavor Text

interface/scripted/statWindow/statWindow.config, scripts/raceEffects.config, species/moogle.species.patch
I have added my **Ivalice Moogle** mod to FR.
=> Added Moogles

species/moogle.species.patch
Forgot to mention that they get an extra mech body part (built into the race-mod itself.)
That's been taken care of.
=> Moogles Updated

interface/scripted/statWindow/statWindow.config
I don't understand some of the "changes" GitHub keeps showing me, and overall, GH is a mess.
However, these guys are missing from the list. I'm adding them onto here myself.
=> add webbers to statWindow.config

species/tauren.species.patch
=> Fixes tauren.species.patch

scripts/raceEffects.config, species/tirastrolls.species.patch, stats/effects/passive/trolllighteffect.lua
converts troll race from... random stuff slapped together into a cohesive tank race
=> makes trolls more better

scripts/raceEffects.config, species/moogle.species.patch
**Buffs**
- Cosmic Resist: 20%
- Charisma Effect
**Nerfs**
- Shadow Weakness: 10%
- Worse at swimming
=> Moogle Update

scripts/raceEffects.config, species/webber.species.patch
Added 5% electric weakness because of silk collection ability and immunity to plagued food.
Updated .species to reflect these changes.
=> Wrath of the tiny in-mod features.

scripts/raceEffects.config, species/inkling.species.patch
Thanks for making this much more public and accessible to other race modders!
After literally forever, here's my contribution. I hope they're not too broken, and I hope the different interactions with different liquids + biomes works! Feel free to edit  if things are overwhelming or broken somewhere.. the latter wouldn't surprise me, even if I'm pretty sure the JSON checks out.
=> Inkling Race Update

interface/scripted/statWindow/statWindow.config, scripts/raceEffects.config, species/eevee.species.patch, species/elysian.species.patch, species/fennix.species.patch
I'm remaking my old mods, mostly from the ground up, alongside my friend, PK.
I thought I may as well add compatibility to Frackin Races as I get the Eevee mod ready for public release.
=> Eevee, Elysian, and Fennix support

stats/effects/passive/starvingedgefloran.lua, stats/effects/regeneration/lightregenfloran.lua
wouldnt be me if something didnt mess up. this time, I goofed on a big math rule: ORDER MATTERS
1+ 0.3 * x is 1 + ( 0.3 * x ) not ( 1 + 0.3 ) * x, dumbdumb Khe.
=> fix for floran energy

items/active/raceEffectEnabler/raceEffectEnabler.lua, scripts/raceEffects.config, species/moogle.species.patch, tech/other/flight_moogle.tech, tech/other/moogleglide.lua, tech/other/moogleglide.tech
Fixed Moogles to have the **slowfall/gliding** tech (including compatibility for the tech enabler item), and further balance tweaks, including reverting fall speed to normal as it's now done by the tech instead of being automatic.
=> Moogle Tech System Update

scripts/raceEffects.config
Adds 'isCarnivore' to Arachne. That's it.
=> Arachne diet thing

species/mantizi.raceeffect
reapplies the lost changes from ef6de77 and pretties up the json cause why not
=> fix mantizi

species/spiritguardian.raceeffect, species/spiritguardian.species.patch
This error causes a crash for my users. An unofficial patch has been put out to remedy this issue for them and will be removed when this PR is merged + the change is made live on Steam
=> Fix a silly mistake of forgetting an end quote.

stats/bonuses/lucarioAuraBerserk.lua
I am still learning lua and got some help to understand how to fix this but I finally got it to work in game. One part of it was missing a = which was the easy part. Although what was causing the lua to break was the lack of values for powerMod, protectionMod, and critMod on Init, which has been added, otherwise was coming up with a nil.
I made sure to examine the file under update to make sure the values I put under init were correct.
=> Aura Berserk Fix

items/generic/meat/rawpoultry.consumable.patch, scripts/fr_scripts/liquidEffect.lua
places debug code to try to find the origin of weird bug
also stops npcs from sploding if weird bug occurs
=> add investigative debug code

stats/deprecated/carnivorefood.statuseffect
restores missing deprecated effect, stopping some characters from breaking
=> add missing deprecated

scripts/fr_scripts/aerialEffect.lua, scripts/fr_scripts/envEffects.lua, scripts/fr_scripts/floranStuff.lua, scripts/fr_scripts/lightEffect.lua, scripts/fr_scripts/lightEffectNightar.lua, scripts/fr_scripts/novakidStuff.lua, scripts/fr_scripts/weaponEffects.lua, scripts/raceEffects.lua, species/skath.raceeffect
removed the automatic persistent clear, added clears to all of the FR scripts
(this is for racial scripts only)
=> clear effects more

species/fukirhos.raceeffect, species/veluu.raceeffect, stats/effects/food/foodBase.lua
was gonna be that typo fix but you got to it first, pushing so there's no difference between two master branches
ok now there's an actual fix in here pls accept
=> just some dern format fixin

scripts/fr_scripts/liquidEffect.lua
just updatin that debug code to account for new information and give more info
=> update debug code

species/eevee.raceeffect, species/eevee.species.patch, species/elysian.raceeffect, species/elysian.species.patch, species/fennix.raceeffect, species/fennix.species.patch
General buffs and debuffs to different things to make the races seem a bit less like glass cannons.
Sometimes I wonder what I was thinking with some of the things I put in.
=> Tweaking GalaxyFoxes

species/mantid.raceeffect, species/mantid.species.patch
Alright, I finally whipped together the stats for my race, the Mantids. Admittedly they're fairly similar to Thelusians, what with also being bugs and all that, but with more offense and mobility and less tankiness.
I've tried to make sure all my brackets, commas and semicolons are in the right places but I really have very little idea what I'm doing with this coding business.
Anyway, thanks for the great mod, keep up the awesome work.
=> Mantid species support

species/lucario.species.patch
I left the description for a few months, and found that someone rewrote it, and then left it unfinished.
=> Rewrite stat description to match lucario.raceeffects

items/generic/food/tier5/eyebowls.consumable.patch
=> Punctuation

scripts/fr_weaponscripts/velocitybonus.lua, species/fenerox.raceeffect
after years of this effect mysteriously not existing despite everyone believing that it did in fact exist, it now actually exists
have fun
=> the fenerox velocity bonus

species/protogenrace1.raceeffect, species/protogenrace1.species.patch
A quick and dirty patch for my Protogen race mod for Frackin' Races.
=> Protogen race patch

species/remorian.raceeffect, species/remorian.species.patch
I'd like to add Remorian support to the FR mod. I have the .raceeffect and .patch files here ready to go. If there's anything else that I need to provide and/or change, please tell me.
-Thanks in advance
=> Add Remorian support to FR

species/protogenrace1.raceeffect, species/protogenrace1.species.patch
Racial strengths/weaknesses rebalance through community feedback
=> Protogen race balance pass

species/irken.raceeffect, species/irken.species.patch
just wanted to submit a support for the irkens so they have their own stats. just trying to make a more up to date frackin irkens
=> irken race support

stats/__STAT_LIST, stats/__STAT_LIST.TXT
I was angry that I couldn't see an easy list of every stat possible for use in FR's `stats` array.
I fixed that problem.
c:
=> Append a big list of every possible stat.

species/irken.raceeffect, species/mantid.raceeffect, species/pygs.raceeffect
It was missing its end quote on `stat` and didn't have a comma at the end
=> Fix malformed json data

species/spiritguardian.raceeffect, species/spiritguardian.species.patch
=> Racial nerfs / tweaks

species/irken.raceeffect, species/lutrin.raceeffect, species/lutrin.species.patch
Thanks to the feedback I've gotten, I feel like this is what should be put in for them.
=> Lutrin Stat-tweaks, final version.

species/lucario.raceeffect, species/lucario.species.patch
Hopefully I didnt f this up now.
=> Lucario Protofix

interface/scripted/fu_multiupgrade/fu_multiupgrade.lua
=> upgradabletool

scripts/fr_scripts/feneroxStuff.lua, scripts/fr_scripts/floranStuff.lua, scripts/fr_scripts/healthRegen.lua, scripts/fr_scripts/novakidStuff.lua
crushed immortality of  races affected by FR scripted hp regen
=> no immortality allowed

items/active/weapons/melee/abilities/hammer/hammersmash.lua, scripts/raceEffects.lua, stats/bonuses/frnpcspecialhandler.lua, stats/bonuses/frnpcspecialhandler.statuseffect, stats/bonuses/lastreeFoodBonus.lua, stats/effects/heal/heal.lua, stats/effects/movement/raceavianmovement.lua, stats/effects/passive/trolllighteffect.lua, stats/effects/regeneration/darkregenfenerox.lua, stats/effects/regeneration/foodregen.lua, stats/effects/regeneration/indixregen.lua, stats/effects/regeneration/lightregen.lua, stats/effects/regeneration/regen_healingwater.lua, stats/effects/regeneration/regenerationminor.lua, stats/effects/slimeslow/slimeslow.lua, stats/effects/tarslow/tarslow.lua, stats/effects/weakpoison/weakpoison.lua, stats/effects/wet/wet.lua
Sometimes, you need to drive the nail so deep in their skull that it comes out their chin. Damn NPCs
=> further immortality fixes
